default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: post
  password: desenv
  host: 172.26.6.151
  port: 5432

development:
  <<: *default
  database: siscar_development

test:
  <<: *default
  database: siscar_test

production:
  <<: *default
  database: siscar_production
