default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root #post
  password: root #desenv
  host: localhost #172.26.6.151
  port: 5432

development:
  <<: *default
  database: siscar_development

test:
  <<: *default
  database: siscar_test

production:
  <<: *default
  database: siscar_production
